name: release

on:
  push:
    tags:
      - v*

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: get latest tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        id: get-latest-tag
        with:
          fallback: latest

      - name: setup release environment
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}' > .release-env

      - name: Build
        run: |
          sudo apt-get update && sudo apt-get install -y musl-tools upx-ucl
          export STATIC=1
          make juicefs.linux

      - name: Archives
        run: |
          mkdir -p /tmp/build
          tar -zcvf /tmp/build/juicefs-${{ steps.get-latest-tag.outputs.tag }}-linux-amd64.tar.gz ./juicefs
  
      - name: 'Release'
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: /tmp/build/juicefs-${{ steps.get-latest-tag.outputs.tag }}-linux-amd64.tar.gz
  
      - name: Release public files
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.get-latest-tag.outputs.tag }} Release
          tag_name: ${{ steps.get-latest-tag.outputs.tag }}
          repository: eball/juicefs-ext-public
          files: |
            /tmp/build/juicefs-${{ steps.get-latest-tag.outputs.tag }}-linux-amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}