name: release

on:
  push:
    tags:
      - v*

jobs:
  releaser:
    ## keep latest version
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: get latest tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        id: get-latest-tag
        with:
          fallback: latest

      - name: setup release environment
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}' > .release-env

      - name: goreleaser release
        run: make release

